export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
export const GET_AUTH_FAILURE = "GET_AUTH_FAILURE";

export const GET_DSM_SUPERVISOR_REQUEST = "GET_DSM_SUPERVISOR_REQUEST";
export const GET_DSM_SUPERVISOR_SUCCESS = "GET_DSM_SUPERVISOR_SUCCESS";
export const GET_DSM_SUPERVISOR_FAILURE = "GET_DSM_SUPERVISOR_FAILURE";

export const GET_CDP_SUPERVISOR_REQUEST = "GET_CDP_SUPERVISOR_REQUEST";
export const GET_CDP_SUPERVISOR_SUCCESS = "GET_CDP_SUPERVISOR_SUCCESS";
export const GET_CDP_SUPERVISOR_FAILURE = "GET_CDP_SUPERVISOR_FAILURE";

export const GET_CLIENT_SAME_DSM_SUPERVISOR_REQUEST = "GET_CLIENT_SAME_DSM_SUPERVISOR_REQUEST";
export const GET_CLIENT_SAME_DSM_SUPERVISOR_SUCCESS = "GET_CLIENT_SAME_DSM_SUPERVISOR_SUCCESS";
export const GET_CLIENT_SAME_DSM_SUPERVISOR_FAILURE = "GET_CLIENT_SAME_DSM_SUPERVISOR_FAILURE";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
