export const ADD_DOCTOR_REQUEST = "ADD_DOCTOR_REQUEST";
export const ADD_DOCTOR_SUCCESS = "ADD_DOCTOR_SUCCESS";
export const ADD_DOCTOR_FAILURE = "ADD_DOCTOR_FAILURE";

export const FETCH_DOCTORS_REQUEST = "FETCH_DOCTORS_REQUEST";
export const FETCH_DOCTORS_SUCCESS = "FETCH_DOCTORS_SUCCESS";
export const FETCH_DOCTORS_FAILURE = "FETCH_DOCTORS_FAILURE";

export const FETCH_DOCTORS_BY_USER_ID_REQUEST = "FETCH_DOCTORS_BY_USER_ID_REQUEST";
export const FETCH_DOCTORS_BY_USER_ID_SUCCESS = "FETCH_DOCTORS_BY_USER_ID_SUCCESS";
export const FETCH_DOCTORS_BY_USER_ID_FAILURE = "FETCH_DOCTORS_BY_USER_ID_FAILURE";

export const FETCH_INVITED_DOCTORS_REQUEST = "FETCH_INVITED_DOCTORS_REQUEST";
export const FETCH_INVITED_DOCTORS_SUCCESS = "FETCH_INVITED_DOCTORS_SUCCESS";
export const FETCH_INVITED_DOCTORS_FAILURE = "FETCH_INVITED_DOCTORS_FAILURE";

export const FETCH_LAST_DOCTOR_REQUEST = "FETCH_LAST_DOCTOR_REQUEST";
export const FETCH_LAST_DOCTOR_SUCCESS = "FETCH_LAST_DOCTOR_SUCCESS";
export const FETCH_LAST_DOCTOR_FAILURE = "FETCH_LAST_DOCTOR_FAILURE";