export const ADD_ACTION_REQUEST = "ADD_ACTION_REQUEST";
export const ADD_ACTION_SUCCESS = "ADD_ACTION_SUCCESS";
export const ADD_ACTION_FAILURE = "ADD_ACTION_FAILURE";

export const FETCH_ACTIONS_REQUEST = "FETCH_ACTIONS_REQUEST";
export const FETCH_ACTIONS_SUCCESS = "FETCH_ACTIONS_SUCCESS";
export const FETCH_ACTIONS_FAILURE = "FETCH_ACTIONS_FAILURE";

export const FETCH_ACTION_BY_ID_REQUEST = "FETCH_ACTION_BY_ID_REQUEST";
export const FETCH_ACTION_BY_ID_SUCCESS = "FETCH_ACTION_BY_ID_SUCCESS";
export const FETCH_ACTION_BY_ID_FAILURE = "FETCH_ACTION_BY_ID_FAILURE";

export const FETCH_ACTION_BY_USER_ID_REQUEST = "FETCH_ACTION_BY_USER_ID_REQUEST";
export const FETCH_ACTION_BY_USER_ID_SUCCESS = "FETCH_ACTION_BY_USER_ID_SUCCESS";
export const FETCH_ACTION_BY_USER_ID_FAILURE = "FETCH_ACTION_BY_USER_ID_FAILURE";

export const UPDATE_ACTION_BY_ID_REQUEST = "UPDATE_ACTION_BY_ID_REQUEST";
export const UPDATE_ACTION_BY_ID_SUCCESS = "UPDATE_ACTION_BY_ID_SUCCESS";
export const UPDATE_ACTION_BY_ID_FAILURE = "UPDATE_ACTION_BY_ID_FAILURE";

export const FETCH_VM_ACTIONS_BY_USER_ID_REQUEST = "FETCH_VM_ACTIONS_BY_USER_ID_REQUEST";
export const FETCH_VM_ACTIONS_BY_USER_ID_SUCCESS = "FETCH_VM_ACTIONS_BY_USER_ID_SUCCESS";
export const FETCH_VM_ACTIONS_BY_USER_ID_FAILURE = "FETCH_VM_ACTIONS_BY_USER_ID_FAILURE";

export const FETCH_VM_VALIDATED_ACTIONS_BY_USER_ID_REQUEST = "FETCH_VM_VALIDATED_ACTIONS_BY_USER_ID_REQUEST";
export const FETCH_VM_VALIDATED_ACTIONS_BY_USER_ID_SUCCESS = "FETCH_VM_VALIDATED_ACTIONS_BY_USER_ID_SUCCESS";
export const FETCH_VM_VALIDATED_ACTIONS_BY_USER_ID_FAILURE = "FETCH_VM_VALIDATED_ACTIONS_BY_USER_ID_FAILURE";

export const FETCH_DSM_VALIDATED_ACTIONS_BY_USER_ID_REQUEST = "FETCH_DSM_VALIDATED_ACTIONS_BY_USER_ID_REQUEST";
export const FETCH_DSM_VALIDATED_ACTIONS_BY_USER_ID_SUCCESS = "FETCH_DSM_VALIDATED_ACTIONS_BY_USER_ID_SUCCESS";
export const FETCH_DSM_VALIDATED_ACTIONS_BY_USER_ID_FAILURE = "FETCH_DSM_VALIDATED_ACTIONS_BY_USER_ID_FAILURE";

export const FETCH_CDP_VALIDATED_ACTIONS_BY_USER_ID_REQUEST = "FETCH_CDP_VALIDATED_ACTIONS_BY_USER_ID_REQUEST";
export const FETCH_CDP_VALIDATED_ACTIONS_BY_USER_ID_SUCCESS = "FETCH_CDP_VALIDATED_ACTIONS_BY_USER_ID_SUCCESS";
export const FETCH_CDP_VALIDATED_ACTIONS_BY_USER_ID_FAILURE = "FETCH_CDP_VALIDATED_ACTIONS_BY_USER_ID_FAILURE";

export const FETCH_DSM_REJECTED_ACTIONS_BY_USER_ID_REQUEST = "FETCH_DSM_REJECTED_ACTIONS_BY_USER_ID_REQUEST";
export const FETCH_DSM_REJECTED_ACTIONS_BY_USER_ID_SUCCESS = "FETCH_DSM_REJECTED_ACTIONS_BY_USER_ID_SUCCESS";
export const FETCH_DSM_REJECTED_ACTIONS_BY_USER_ID_FAILURE = "FETCH_DSM_REJECTED_ACTIONS_BY_USER_ID_FAILURE";

export const FETCH_CDP_REJECTED_ACTIONS_BY_USER_ID_REQUEST = "FETCH_CDP_REJECTED_ACTIONS_BY_USER_ID_REQUEST";
export const FETCH_CDP_REJECTED_ACTIONS_BY_USER_ID_SUCCESS = "FETCH_CDP_REJECTED_ACTIONS_BY_USER_ID_SUCCESS";
export const FETCH_CDP_REJECTED_ACTIONS_BY_USER_ID_FAILURE = "FETCH_CDP_REJECTED_ACTIONS_BY_USER_ID_FAILURE";

export const FETCH_SPEAKER_ACTIONS_BY_USER_ID_REQUEST = "FETCH_SPEAKER_ACTIONS_BY_USER_ID_REQUEST";
export const FETCH_SPEAKER_ACTIONS_BY_USER_ID_SUCCESS = "FETCH_SPEAKER_ACTIONS_BY_USER_ID_SUCCESS";
export const FETCH_SPEAKER_ACTIONS_BY_USER_ID_FAILURE = "FETCH_SPEAKER_ACTIONS_BY_USER_ID_FAILURE";

export const VALIDATE_STATUS_ACTION_BY_ID_REQUEST = "VALIDATE_STATUS_ACTION_BY_ID_REQUEST";
export const VALIDATE_STATUS_ACTION_BY_ID_SUCCESS = "VALIDATE_STATUS_ACTION_BY_ID_SUCCESS";
export const VALIDATE_STATUS_ACTION_BY_ID_FAILURE = "VALIDATE_STATUS_ACTION_BY_ID_FAILURE";

export const VALIDATE_DSM_STATUS_ACTION_BY_ID_REQUEST = "VALIDATE_DSM_STATUS_ACTION_BY_ID_REQUEST";
export const VALIDATE_DSM_STATUS_ACTION_BY_ID_SUCCESS = "VALIDATE_DSM_STATUS_ACTION_BY_ID_SUCCESS";
export const VALIDATE_DSM_STATUS_ACTION_BY_ID_FAILURE = "VALIDATE_DSM_STATUS_ACTION_BY_ID_FAILURE";

export const VALIDATE_DSM_SPEAKER_STATUS_ACTION_BY_ID_REQUEST = "VALIDATE_DSM_SPEAKER_STATUS_ACTION_BY_ID_REQUEST";
export const VALIDATE_DSM_SPEAKER_STATUS_ACTION_BY_ID_SUCCESS = "VALIDATE_DSM_SPEAKER_STATUS_ACTION_BY_ID_SUCCESS";
export const VALIDATE_DSM_SPEAKER_STATUS_ACTION_BY_ID_FAILURE = "VALIDATE_DSM_SPEAKER_STATUS_ACTION_BY_ID_FAILURE";

export const VALIDATE_VM_STATUS_ACTION_BY_ID_REQUEST = "VALIDATE_VM_STATUS_ACTION_BY_ID_REQUEST";
export const VALIDATE_VM_STATUS_ACTION_BY_ID_SUCCESS = "VALIDATE_VM_STATUS_ACTION_BY_ID_SUCCESS";
export const VALIDATE_VM_STATUS_ACTION_BY_ID_FAILURE = "VALIDATE_VM_STATUS_ACTION_BY_ID_FAILURE";

export const VALIDATE_CDP_FIRST_STATUS_ACTION_BY_ID_REQUEST = "VALIDATE_CDP_FIRST_STATUS_ACTION_BY_ID_REQUEST";
export const VALIDATE_CDP_FIRST_STATUS_ACTION_BY_ID_SUCCESS = "VALIDATE_CDP_FIRST_STATUS_ACTION_BY_ID_SUCCESS";
export const VALIDATE_CDP_FIRST_STATUS_ACTION_BY_ID_FAILURE = "VALIDATE_CDP_FIRST_STATUS_ACTION_BY_ID_FAILURE";

export const VALIDATE_CDP_STATUS_ACTION_BY_ID_REQUEST = "VALIDATE_CDP_STATUS_ACTION_BY_ID_REQUEST";
export const VALIDATE_CDP_STATUS_ACTION_BY_ID_SUCCESS = "VALIDATE_CDP_STATUS_ACTION_BY_ID_SUCCESS";
export const VALIDATE_CDP_STATUS_ACTION_BY_ID_FAILURE = "VALIDATE_CDP_STATUS_ACTION_BY_ID_FAILURE";

export const VALIDATE_MED_FIRST_STATUS_ACTION_BY_ID_REQUEST = "VALIDATE_MED_FIRST_STATUS_ACTION_BY_ID_REQUEST";
export const VALIDATE_MED_FIRST_STATUS_ACTION_BY_ID_SUCCESS = "VALIDATE_MED_FIRST_STATUS_ACTION_BY_ID_SUCCESS";
export const VALIDATE_MED_FIRST_STATUS_ACTION_BY_ID_FAILURE = "VALIDATE_MED_FIRST_STATUS_ACTION_BY_ID_FAILURE";

export const VALIDATE_MED_STATUS_ACTION_BY_ID_REQUEST = "VALIDATE_MED_STATUS_ACTION_BY_ID_REQUEST";
export const VALIDATE_MED_STATUS_ACTION_BY_ID_SUCCESS = "VALIDATE_MED_STATUS_ACTION_BY_ID_SUCCESS";
export const VALIDATE_MED_STATUS_ACTION_BY_ID_FAILURE = "VALIDATE_MED_STATUS_ACTION_BY_ID_FAILURE";

export const DENY_STATUS_DSM_ACTION_BY_ID_REQUEST = "DENY_STATUS_DSM_ACTION_BY_ID_REQUEST";
export const DENY_STATUS_DSM_ACTION_BY_ID_SUCCESS = "DENY_STATUS_DSM_ACTION_BY_ID_SUCCESS";
export const DENY_STATUS_DSM_ACTION_BY_ID_FAILURE = "DENY_STATUS_DSM_ACTION_BY_ID_FAILURE";

export const DENY_STATUS_CDP_ACTION_BY_ID_REQUEST = "DENY_STATUS_CDP_ACTION_BY_ID_REQUEST";
export const DENY_STATUS_CDP_ACTION_BY_ID_SUCCESS = "DENY_STATUS_CDP_ACTION_BY_ID_SUCCESS";
export const DENY_STATUS_CDP_ACTION_BY_ID_FAILURE = "DENY_STATUS_CDP_ACTION_BY_ID_FAILURE";

export const DELETE_ACTION_BY_ID_REQUEST = "DELETE_ACTION_BY_ID_REQUEST";
export const DELETE_ACTION_BY_ID_SUCCESS = "DELETE_ACTION_BY_ID_SUCCESS";
export const DELETE_ACTION_BY_ID_FAILURE = "DELETE_ACTION_BY_ID_FAILURE";

export const RETURN_ACTION_BY_ID_REQUEST = "RETURN_ACTION_BY_ID_REQUEST";
export const RETURN_ACTION_BY_ID_SUCCESS = "RETURN_ACTION_BY_ID_SUCCESS";
export const RETURN_ACTION_BY_ID_FAILURE = "RETURN_ACTION_BY_ID_FAILURE";

export const DISARCHIVAGE_ACTION_BY_ID_REQUEST = "DISARCHIVAGE_ACTION_BY_ID_REQUEST";
export const DISARCHIVAGE_ACTION_BY_ID_SUCCESS = "DISARCHIVAGE_ACTION_BY_ID_SUCCESS";
export const DISARCHIVAGE_ACTION_BY_ID_FAILURE = "DISARCHIVAGE_ACTION_BY_ID_FAILURE";

export const ARCHIVAGE_ACTION_BY_ID_REQUEST = "ARCHIVAGE_ACTION_BY_ID_REQUEST";
export const ARCHIVAGE_ACTION_BY_ID_SUCCESS = "ARCHIVAGE_ACTION_BY_ID_SUCCESS";
export const ARCHIVAGE_ACTION_BY_ID_FAILURE = "ARCHIVAGE_ACTION_BY_ID_FAILURE";

export const FINISH_ACTION_BY_ID_REQUEST = "FINISH_ACTION_BY_ID_REQUEST";
export const FINISH_ACTION_BY_ID_SUCCESS = "FINISH_ACTION_BY_ID_SUCCESS";
export const FINISH_ACTION_BY_ID_FAILURE = "FINISH_ACTION_BY_ID_FAILURE";

export const MESSAGING_VALIDATION_REQUEST = "MESSAGING_VALIDATION_REQUEST";
export const MESSAGING_VALIDATION_SUCCESS = "MESSAGING_VALIDATION_SUCCESS";
export const MESSAGING_VALIDATION_FAILURE = "MESSAGING_VALIDATION_FAILURE";

export const MESSAGING_REJECTION_REQUEST = "MESSAGING_REJECTION_REQUEST";
export const MESSAGING_REJECTION_SUCCESS = "MESSAGING_REJECTION_SUCCESS";
export const MESSAGING_REJECTION_FAILURE = "MESSAGING_REJECTION_FAILURE";

export const SERVICES_REQUEST = "SERVICES_REQUEST";
export const SERVICES_SUCCESS = "SERVICES_SUCCESS";
export const SERVICES_FAILURE = "SERVICES_FAILURE";

export const DOWNLOAD_FILE_REQUEST = "DOWNLOAD_FILE_REQUEST";
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS";
export const DOWNLOAD_FILE_FAILURE = "DOWNLOAD_FILE_FAILURE";