export const ADD_FILE_REQUEST = "ADD_FILE_REQUEST";
export const ADD_FILE_SUCCESS = "ADD_FILE_SUCCESS";
export const ADD_FILE_FAILURE = "ADD_FILE_FAILURE";

export const RETRIEVE_FILE_REQUEST = "RETRIEVE_FILE_REQUEST";
export const RETRIEVE_FILE_SUCCESS = "RETRIEVE_FILE_SUCCESS";
export const RETRIEVE_FILE_FAILURE = "RETRIEVE_FILE_FAILURE";

