export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILURE = "ADD_NOTE_FAILURE";

export const FETCH_NOTES_BY_ACTION_SENDER_REQUEST = "FETCH_NOTES_BY_ACTION_SENDER_REQUEST";
export const FETCH_NOTES_BY_ACTION_SENDER_SUCCESS = "FETCH_NOTES_BY_ACTION_SENDER_SUCCESS";
export const FETCH_NOTES_BY_ACTION_SENDER_FAILURE = "FETCH_NOTES_BY_ACTION_SENDER_FAILURE";
