export const ADD_LOCALISATION_REQUEST = "ADD_LOCALISATION_REQUEST";
export const ADD_LOCALISATION_SUCCESS = "ADD_LOCALISATION_SUCCESS";
export const ADD_LOCALISATION_FAILURE = "ADD_LOCALISATION_FAILURE";

export const FETCH_LOCALISATIONS_REQUEST = "FETCH_LOCALISATIONS_REQUEST";
export const FETCH_LOCALISATIONS_SUCCESS = "FETCH_LOCALISATIONS_SUCCESS";
export const FETCH_LOCALISATIONS_FAILURE = "FETCH_LOCALISATIONS_FAILURE";
