export const FETCH_LOCALISATIONS_REQUEST = "FETCH_LOCALISATIONS_REQUEST";
export const FETCH_LOCALISATIONS_SUCCESS = "FETCH_LOCALISATIONS_SUCCESS";
export const FETCH_LOCALISATIONS_FAILURE = "FETCH_LOCALISATIONS_FAILURE";
