export const ADD_VM_MAIL_REQUEST = "ADD_VM_MAIL_REQUEST";
export const ADD_VM_MAIL_SUCCESS = "ADD_VM_MAIL_SUCCESS";
export const ADD_VM_MAIL_FAILURE = "ADD_VM_MAIL_FAILURE";

export const ADD_SUPERVISORS_MAIL_REQUEST = "ADD_SUPERVISORS_MAIL_REQUEST";
export const ADD_SUPERVISORS_MAIL_SUCCESS = "ADD_SUPERVISORS_MAIL_SUCCESS";
export const ADD_SUPERVISORS_MAIL_FAILURE = "ADD_SUPERVISORS_MAIL_FAILURE";

